name: ViaRewind
version: ${project.version}
main: com.viaversion.viarewind.BukkitPlugin
api-version: 1.13
folia-supported: true

authors: [Gerrygames, FlorianMichael/EnZaXD, creeper123321123]
website: https://viaversion.com/rewind

load: STARTUP
depend: [ViaVersion]
softdepend: [ViaBackwards]
